### ISSUE TITLE
提出用issue

### ISSUE THREAD

**Issue by tkhero555** [tkhero555/Puri.log#65]
## 各種情報
Puri.log
https://purilog-2a85943c9f18.herokuapp.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] linebot
- [x] line会員登録
- [ ] 会員登録
- [ ] ログイン
- [x] 食事と便の記録
- [x] 食事と便の相関を判定するアルゴリズム
- [x] 相性判定結果の一覧表示

## READMEレビュー時から変更した機能
【MVPリリース時点で作らなくなった機能】
- 会員登録
- ログイン

【追加した機能】
- ゲストログイン機能

## サービスイメージがわかるようなスクリーンショット等
マイページ
[![Image from Gyazo](https://i.gyazo.com/2d14f503ff94ebb5c1ae75a5d1da42a1.png)](https://gyazo.com/2d14f503ff94ebb5c1ae75a5d1da42a1)
linebot
[![Image from Gyazo](https://i.gyazo.com/a8b73ebec7d968b0aa0f4db42e5b4a1e.png)](https://gyazo.com/a8b73ebec7d968b0aa0f4db42e5b4a1e)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
